export const neededAssessmentFamQues = [
  {
    id: 'ward',
    type: 'string',
    note: 'ward you lived',
    title: 'Ward',
  },
  {
    id: 'village',
    type: 'string',
    note: 'village you lived',
    title: 'Village',
  },
  {
    id: 'houseHead',
    type: 'dropdown',
    note: 'Household head',
    title: 'Household head',
    data: 'members',
    dataLabel: 'name',
    dataKey: 'name',
  },
  {
    id: 'address',
    type: 'string',
    title: 'Address where you lived',
    note: 'Address where you lived',
  },
  {
    id: 'contactNo',
    type: 'number',
    note: 'Contact no',
    title: 'Contact no',
    charLimit: 10,
  },
  {
    id: 'rationCardNo',
    type: 'number',
    note: 'Ration Card number',
    title: 'Ration Card no',
    required: true,
    charLimit: 12,
  },
  {
    id: 'rationCategory',
    type: 'dropdown',
    note: 'Ration category',
    title: 'Ration category',
    options: [
      { label: 'White', value: 'white' },
      { label: 'Yellow', value: 'yellow' },
      { label: 'Pink', value: 'pink' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'caste',
    type: 'dropdown',
    note: 'Caste of household head',
    title: 'Caste of household head',
    options: [
      { label: 'General', value: 'general' },
      { label: 'Other Backward Class', value: 'obc' },
      { label: 'Scheduled caste', value: 'sc' },
      { label: 'Scheduled tribe', value: 'st' },
      { label: 'Other, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'anganwadiMembers',
    type: 'number',
    note: 'Total number of children enrolled in Anganwadi centers',
    title: 'Total number of children enrolled in Anganwadi centers',
    condition: {
      type: 'member_filter',
      filters: [
        {
          type: 'less_than',
          field: 'dob',
          value: 1000 * 60 * 60 * 24 * 365 * 5,
        },
      ],
      then: 'auto_fill',
    },
  },
  {
    id: 'malnutritionChild',
    type: 'multi-dropdown',
    note: 'Any children with malnutrition',
    title: 'Any children with malnutrition',
    data: 'members',
    dataLabel: 'name',
    dataKey: 'name',
    condition: {
      type: 'member_filter',
      filters: [
        {
          type: 'less_than',
          field: 'dob',
          value: 1000 * 60 * 60 * 24 * 365 * 5,
        },
      ],
      then: 'options',
    },
  },
  {
    id: 'pregnantWomen',
    type: 'multi-dropdown',
    note: 'Pregnant women in the family',
    title: 'Pregnant women in the family',
    data: 'members',
    dataLabel: 'name',
    dataKey: 'name',
    condition: {
      type: 'member_filter',
      filters: [{ type: 'equal', field: 'gender', value: 'female' }],
      then: 'options',
    },
  },
  {
    id: 'lactatingWomen',
    type: 'multi-dropdown',
    note: 'Lactating mothers in the family',
    title: 'Lactating mothers in the family',
    data: 'members',
    dataLabel: 'name',
    dataKey: 'name',
    condition: {
      type: 'member_filter',
      filters: [{ type: 'equal', field: 'gender', value: 'female' }],
      then: 'options',
    },
  },
  {
    id: 'foodAssist',
    type: 'dropdown',
    note: 'Is the present food assistance sufficient',
    title: 'Is the present food assistance sufficient',
    options: [
      { label: 'Yes', value: 'yes' },
      { label: 'No, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'foodAssistPeriod',
    type: 'date',
    note: 'How long do you need food assistance',
    title: 'How long do you need food assistance',
    condition: {
      type: 'not_equal',
      field: 'foodAssist',
      value: 'yes',
      then: 'show',
    },
  },
  {
    id: 'healthInsurance',
    type: 'dropdown',
    note: 'Do you have health insurance coverage',
    title: 'Do you have health insurance coverage',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'houseType',
    type: 'multi-dropdown',
    title: ' Type of house ',
    note: ' Type of house ',
    options: [
      {
        value: 'Permanent structure (pucca) ',
        label: 'Permanent structure (pucca) ',
      },
      {
        value: 'House built with govt. assistance',
        label: 'House built with govt. assistance ',
      },
      { value: 'Rented', label: 'Rented' },
      { value: 'Paadi (Layam)', label: 'Paadi (Layam)' },
      { value: 'other', label: 'Others , Specify' },
    ],
  },
  {
    id: 'extendResidentialLand',
    type: 'string',
    note: 'Extend (area) of residential land',
    title: 'Extend (area) of residential land',
  },
  {
    id: 'vehiclesList',
    type: 'multi-dropdown',
    note: 'Do you possess any Vehicle before the disaster',
    title: 'Do you possess any Vehicle before the disaster',
    options: [
      { value: 'two wheeler', label: 'Two Wheeler' },
      { value: 'three wheeler', label: 'Three Wheeler' },
      { value: 'four wheeler', label: 'Four Wheeler' },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
  },
  {
    id: 'vehiclesDamaged',
    type: 'multi-dropdown',
    note: 'Do you possess any Vehicle damaged in the disaster',
    title: 'Do you possess any Vehicle damaged in the disaster',
    options: [
      { value: 'two wheeler', label: 'Two Wheeler' },
      { value: 'three wheeler', label: 'Three Wheeler' },
      { value: 'four wheeler', label: 'Four Wheeler' },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
  },
  {
    id: 'vehicleDeatils',
    type: 'text-area',
    note: 'vehicle number and details',
    title: 'vehicle number and details',
    condition: {
      type: 'not_null',
      field: 'vehiclesList',
      then: 'show',
    },
  },
  {
    id: 'monthlyIncome',
    title: 'What was your average monthly family income',
    type: 'dropdown',
    note: 'What was your average monthly family income',
    options: [
      {
        label: 'Less than 5,000',
        value: 'Less than 5,000',
      },
      { label: '5,000 to 10,000', value: '5,000 to 10,000' },
      { label: '10,000 to 20,000', value: '10,000 to 20,000' },
      { label: '20,000 to 30,000', value: '20,000 to 30,000' },
      { label: '30,000 to 40,000', value: '30,000 to 40,000' },
      { label: '40,000 to 50,000', value: '40,000 to 50,000' },
      { label: 'Above 50,000', value: 'Above 50,000' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'primaryIncomeSorce',
    type: 'text',
    note: ' Primary Source of Income',
    title: ' Primary Source of Income',
  },
  {
    id: 'livelihoodAffected',
    type: 'multi-dropdown',
    title: ' Source of livelihood affected or not',
    note: ' Source of livelihood affected or not',
    options: [
      { value: 'Employment Loss', label: 'Employment Loss' },
      { value: 'Loss in Business', label: 'Loss in Business' },
      {
        value: 'Income Loss to daily wage worker',
        label: 'Income Loss to daily wage worker',
      },
      { value: 'Loss of breadwinner', label: 'Loss of breadwinner' },
      { value: 'Loss in animal husbandry', label: 'Loss in animal husbandry' },
      {
        value: 'Loss of agricultural land and crops',
        label: 'Loss of agricultural land and crops',
      },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
  },
  {
    id: 'agriculturalLossLand',
    note: 'Did you incur any loss of agricultural land (area)',
    title: 'Did you incur any loss of agricultural land (area)',
    type: 'string',
  },
  {
    id: 'agriculturalLossCrops',
    note: 'Did you experience any loss of stored crops (quantity)',
    title: 'Did you experience any loss of stored crops (quantity)',
    type: 'string',
  },
  {
    id: 'agriculturalCropsType',
    note: 'Name the Crops Where Loss',
    title: 'Name the Crops Where Loss',
    type: 'string',
    condition: {
      type: 'not_null',
      field: 'agriculturalLossCrops',
      then: 'show',
    },
  },
  {
    id: 'equipmentLoss',
    note: 'Did you lose any equipment/Tools/vehicles ',
    title: 'Did you lose any equipment/Tools/vehicles ',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'cattlePoultryLoss',
    note: 'Have you suffered the loss of any Cattle or Poultry',
    title: 'Have you suffered the loss of any Cattle or Poultry',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify number and type', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'poultryShedLoss',
    note: 'Have you lost any Poultry Shed or Cattle Shed',
    title: 'Have you lost any Poultry Shed or Cattle Shed',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify number and type', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'equipmentLossDetails',
    note: ' Did you lose any equipment or Tools',
    title: ' Did you lose any equipment or Tools',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify the type', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'livelihoodInsurance',
    note: ' Do you have any livelihood Insurance Coverage (agricultural land-crop/animals) ',
    title:
      'Do you have any livelihood Insurance Coverage (agricultural land-crop/animals) ',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify the details', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'socialSecurityPension',
    note: ' Are you or anyone in your family currently a beneficiary of any pension',
    title:
      'Are you or anyone in your family currently a beneficiary of any pension',
    type: 'multi-dropdown',
    options: [
      { label: 'Old Age Pension', value: 'Old Age Pension' },
      { label: 'Widow Pension', value: 'Widow Pension' },
      { label: 'Divyang Pension', value: 'Divyang Pension' },
      { label: 'Others, Specify the details', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'mgnregaScheme',
    note: 'Is anyone in your family a beneficiary of MGNREGA Scheme',
    title: 'Is anyone in your family a beneficiary of MGNREGA Scheme',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify the details', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'documentLoss',
    note: 'Have you lost any of the following legal documents',
    title: 'Have you lost any of the following legal documents',
    type: 'multi-dropdown',
    options: [
      { label: 'No Loss', value: 'no' },
      { label: 'Aadhar Card', value: 'Aadhar Card' },
      { label: 'Government ID Card', value: 'Government ID Card' },
      { label: 'Passport', value: 'Passport' },
      { label: 'Employment Card', value: 'Employment Card' },
      { label: 'Pan Card', value: 'Pan Card' },
      { label: 'Insurance Card', value: 'Insurance Card' },
      { label: 'Driving License', value: 'Driving License' },
      { label: 'ATM Card', value: 'ATM Card' },
      { label: 'Ration Card', value: 'Ration Card' },
      { label: 'Land Document', value: 'Land Document' },
      { label: 'Property Document', value: 'Property Document' },
      { label: 'Birth certificate', value: 'Birth certificate' },
      { label: 'Marriage Certificate', value: 'Marriage Certificate' },
      { label: 'Educational', value: 'Educational' },
      { label: 'Others, Specify the documents', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'documentLoss',
    note: 'Are you part of any special category',
    title: 'Are you part of any special category',
    type: 'multi-dropdown',
    options: [
      { label: 'Elderly only Family (Including Children)', value: 'no' },
      {
        label: 'Women only Family (Including Children)',
        value: 'Women only Family (Including Children)',
      },
      { label: 'Lone survivor', value: 'Lone survivor' },
      { label: 'Children only', value: 'Children only' },
      { label: 'Tribals', value: 'Tribals' },
      { label: 'Transgenders', value: 'Transgenders' },
      { label: 'Others, Specify ', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'kundumbashree',
    note: 'Are you a member of any Kudumbashree community',
    title: 'Are you a member of any Kudumbashree community',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      {
        label: 'If yes, what is the name of your Neighborhood Group (NHG)',
        value: 'other',
      },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'nghInternalLoan',
    note: 'Have you taken any internal loans through your NHG',
    title: 'Have you taken any internal loans through your NHG',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify the amount', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'nhgLinkageLoan',
    note: ' Have you taken any linkage loans through your NHG',
    title: ' Have you taken any linkage loans through your NHG',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify the amount', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'nhgMicroEnterpriseLoan',
    note: ' Have you taken any micro-enterprise loans through your NHG',
    title: 'Have you taken any micro-enterprise loans through your NHG',
    type: 'dropdown',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, Specify the amount', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'support',
    note: 'Any Specific Assistance or Support needed',
    title: 'Any Specific Assistance or Support needed',
    type: 'string',
  },
]
export const neededAssessmentMemQues = [
  {
    id: 'name',
    title: 'Name',
    type: 'string',
    note: 'name of member',
  },
  {
    id: 'dob',
    title: 'Date Of Birth',
    type: 'date',
    note: 'Date Of Birth',
  },
  {
    id: 'gender',
    title: 'Gender',
    type: 'dropdown',
    note: 'Gender of member',
    options: [
      { label: 'Male', value: 'male' },
      { label: 'Female', value: 'female' },
      { label: 'Other, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'position',
    title: 'Position in the family',
    type: 'dropdown',
    note: 'Position in the family According to Head',
    options: [
      { label: 'Son', value: 'son' },
      { label: 'Daughter', value: 'daughter' },
      { label: 'Wife', value: 'wife' },
      { label: 'Husband', value: 'husband' },
      { label: 'Grand Mother', value: 'grandMother' },
      { label: 'Grand Father', value: 'grandFather' },
      { label: 'Head', value: 'head' },
      { label: 'Other, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'maritalStatus',
    title: 'Marital Status ',
    type: 'dropdown',
    note: 'Marital Status ',
    options: [
      { label: 'Married', value: 'married' },
      { label: 'Single', value: 'single' },
      { label: 'Wife', value: 'wife' },
      { label: 'Divorsed', value: 'divorced' },
      { label: 'Widow', value: 'widow' },
      { label: 'Other, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'status',
    title: 'Status',
    type: 'dropdown',
    note: 'Status of member',
    required: true,
    options: [
      { label: 'Missing', value: 'missing' },
      { label: 'Alive', value: 'alive' },
      { label: 'Dead', value: 'dead' },
      { label: 'Hospitalised', value: 'hospital' },
      { label: 'Other, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'aadhaarNo',
    title: 'Aadhaar No',
    note: 'Aadhaar No',
    type: 'number',
    charLimit: 10,
  },
  {
    id: 'injured',
    title: 'Griev Injured',
    type: 'dropdown',
    note: 'Griev Injured ',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'bedRidden',
    title: 'Bed-ridden/ Palliative',
    type: 'dropdown',
    note: 'Bed-ridden/ Palliative',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'psychoAssistant',
    title: 'Psycho-socio assistance/emotional distress',
    type: 'dropdown',
    note: 'Psycho-socio assistance/emotional distress',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes', value: 'yes' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'nursingAssistant',
    title: 'Nursing home assistance for elderly',
    type: 'dropdown',
    note: 'Nursing home assistance for elderly',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes', value: 'yes' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'assistiveDevice',
    title: 'Needs for assistive device',
    type: 'dropdown',
    note: 'Needs for assistive device',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'medicalRequirements',
    title: 'Needs for special medical requirements',
    type: 'dropdown',
    note: 'Needs for special medical requirements',
    options: [
      { label: 'No', value: 'no' },
      { label: 'Yes, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'accommodation',
    title: 'Accommodation in the aftermath of the disaster :',
    type: 'dropdown',
    note: 'Accommodation in the aftermath of the disaster :',
    options: [
      {
        label:
          'Relief Camps (Temporary camps set up by government like schools, halls, etc. or designated Relief Shelters)',
        value: 'camp',
      },
      { label: 'Friends/Relatives places', value: 'Friends/Relatives' },
      { label: 'Rented accommodation', value: 'rented' },
      { label: 'Govt. accommodation', value: 'Govt. accommodation' },
      { label: 'Others, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'campId',
    title: 'Relief Camp',
    type: 'dropdown',
    note: 'Relief Camp',
    data: 'camp_data',
    dataKey: '_id',
    dataLabel: 'name',
    condition: {
      type: 'equal',
      field: 'accommodation',
      value: 'camp',
      then: 'show',
    },
  },
  {
    id: 'course',
    title: 'course',
    type: 'dropdown',
    note: 'course',
    options: [
      {
        label: 'state',
        value: 'state',
      },
      { label: 'CBSC', value: 'cbsc' },
      { label: 'UG', value: 'ug' },
      { label: 'PG', value: 'pg' },
      { label: 'Phd', value: 'phd' },
      { label: 'Not Studing', value: 'Not Studing' },
      { label: 'Others, specify', value: 'other' },
    ],
    dataLabel: 'label',
    dataKey: 'value',
  },
  {
    id: 'courseYear',
    title: 'Course Year',
    note: 'Course Year',
    type: 'number',
    charLimit: 2,
    condition: {
      type: 'not_equal',
      value: 'Not Studing',
      field: 'course',
      then: 'show',
    },
  },
  {
    id: 'institution',
    title: 'School/Institution',
    note: 'School/Institutionr',
    type: 'string',
  },
  {
    id: 'droupOut',
    title: 'DropOut',
    note: 'DropOut',
    type: 'boolean',
  },
  {
    id: 'schoolShift',
    title: 'Are you willing to shift to new school',
    note: 'Are you willing to shift to new school',
    type: 'boolean',
  },
  {
    id: 'prferredEducation',
    title: 'Preferred mode of education regular/open',
    note: 'Preferred mode of education regular(R)/open(O)',
    type: 'dropdown',
    options: [
      { label: 'Regular', value: 'regular' },
      { label: 'Open', value: 'open' },
    ],
  },
  {
    id: 'studyAssist',
    type: 'multi-dropdown',
    note: 'Types of assistance for studying',
    title: 'Types of assistance for studying',
    options: [
      { value: 'Study materials', label: 'Study materials' },
      { value: 'Digital device', label: 'Digital device' },
      { value: 'Transportation', label: 'Transportation' },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
  },
  {
    id: 'qualification',
    note: 'Qualification',
    title: 'Qualification',
    type: 'dropdown',
    options: [
      { value: '`10`', label: '10th' },
      { value: '+2', label: '+2' },
      { value: 'ug', label: 'UG' },
      { value: 'pg', label: 'PG' },
      { value: 'phd', label: 'Phd' },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
  },
  {
    id: 'prevEmploymentStatus',
    note: 'Previous Employment Status',
    title: 'Previous Employment Status',
    type: 'dropdown',
    options: [
      { value: 'Employed', label: 'Employed' },
      { value: 'Unemployed', label: 'Unemployed' },
      { value: 'Self-employed', label: 'Self-employed' },
      {
        value: 'Unemployed due to health condition',
        label: 'Unemployed due to health condition',
      },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
  },
  {
    id: 'prevEmploymentSector',
    note: 'Previous Employment Sector',
    title: 'Previous Employment Sector',
    type: 'dropdown',
    options: [
      { value: 'Govt.', label: 'Government' },
      { value: 'Private', label: 'Private' },
      { value: 'Plantation', label: 'Plantation' },
      { value: 'Ariculture/Allied', label: 'Ariculture/Allied' },
      { value: 'Daily Wage', label: 'Daily Wage' },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
    condition: {
      type: 'not_equal',
      field: 'prevEmploymentStatus',
      value: 'Unemployed',
      then: 'show',
    },
  },
  {
    id: 'unEmploymentReason',
    note: 'Whether Unemployment due to disaster',
    title: 'Whether Unemployment due to disaster',
    type: 'dropdown',
    options: [
      { value: 'Yes', label: 'Yes' },
      { value: 'No', label: 'No' },
      { value: 'other', label: 'Others, specify' },
    ],
    dataKey: 'value',
    dataLabel: 'label',
    condition: {
      type: 'not_equal',
      field: 'prevEmploymentStatus',
      value: 'Unemployed',
      then: 'show',
    },
  },
  {
    id: 'prevEmpSalary',
    note: 'Previous Employment Salary',
    title: 'Previous Employment Salary',
    type: 'number',
    charLimit: 10,
    condition: {
      type: 'not_equal',
      field: 'prevEmploymentStatus',
      value: 'Unemployed',
      then: 'show',
    },
  },
  {
    id: 'skills',
    note: 'Present Skill set',
    title: 'Present Skill set',
    type: 'text-area',
  },
  {
    id: 'livelihoodAssistance',
    note: 'Type of livelihood assistance required ',
    title: 'Type of livelihood assistance required ',
    type: 'text-area',
  },
  {
    id: 'skillingAssistance',
    note: 'Type of skilling assistance required ',
    title: 'Type of skilling assistance required ',
    type: 'text-area',
  },
]

export const defaultNeededAssessmentQues = [
  {
    category: 'Household Profile',
    famQues: [
      'ward',
      'village',
      'houseHead',
      'address',
      'contactNo',
      'rationCardNo',
      'rationCategory',
      'caste',
    ],
    indQues: [
      'name',
      'dob',
      'gender',
      'position',
      'maritalStatus',
      'status',
      'aadhaarNo',
    ],
  },
  {
    category: 'Food Security and Nutrition',
    famQues: [
      'anganwadiMembers',
      'malnutritionChild',
      'pregnantWomen',
      'lactatingWomen',
      'foodAssist',
      'foodAssistPeriod',
    ],
    indQues: [],
  },
  {
    category: 'Health',
    famQues: ['healthInsurance'],
    indQues: [
      'name',
      'injured',
      'bedRidden',
      'psychoAssistant',
      'nursingAssistant',
      'assistiveDevice',
      'medicalRequirements',
    ],
  },
  {
    category: 'Shelter',
    famQues: [
      'houseType',
      'extendResidentialLand',
      'vehiclesList',
      'vehicleDeatils',
      'vehiclesDamaged',
    ],
    indQues: ['accommodation', 'campId'],
  },
  {
    category: 'Education',
    famQues: [],
    indQues: [
      'name',
      'course',
      'courseYear',
      'institution',
      'droupOut',
      'schoolShift',
      'prferredEducation',
      'studyAssist',
    ],
  },
  {
    category: 'Livelihood',
    famQues: ['monthlyIncome', 'primaryIncomeSorce', 'livelihoodAffected'],
    indQues: [
      'name',
      'qualification',
      'prevEmploymentStatus',
      'prevEmploymentSector',
      'unEmploymentReason',
      'prevEmpSalary',
    ],
  },
  {
    category: 'Livelihood and Skill Building Needs',
    famQues: [],
    indQues: ['name', 'skills', 'livelihoodAssistance', 'skillingAssistance'],
  },
  {
    category: 'Agriculture and Allied',
    famQues: [
      'agriculturalLossLand',
      'agriculturalLossCrops',
      'agriculturalCropsType',
      'equipmentLoss',
    ],
    indQues: [],
  },
  {
    category: 'Animal Husbandry',
    famQues: [
      'cattlePoultryLoss',
      'poultryShedLoss',
      'equipmentLossDetails',
      'livelihoodInsurance',
    ],
    indQues: [],
  },
  {
    category: 'Social Security Pension and Loan',
    famQues: ['socialSecurityPension', 'mgnregaScheme', 'documentLoss'],
    indQues: [],
  },
  {
    category: 'Special Category',
    famQues: ['documentLoss'],
    indQues: [],
  },
  {
    category: 'Kudumbashree',
    famQues: [
      'kundumbashree',
      'nghInternalLoan',
      'nhgLinkageLoan',
      'nhgMicroEnterpriseLoan',
      'support',
    ],
    indQues: [],
  },
]

const schema = {
  id: '12',
  title: 'qwer',
  note: 'wefg',
  type: [
    'dropdown',
    'multi-dropdown',
    'string',
    'number',
    'date',
    'boolean',
    'text-area',
    'array',
  ],
  options: ['', '', ''],
  charLimit: 10,
  required: true,
  dataLabel: 'name',
  dataKey: '_id',
  condition: {},
}

const questions = defaultNeededAssessmentQues.map((category) => {
  return {
    category: category.category,
    famQues: category.famQues.map((id) => {
      const question = neededAssessmentFamQues.find((q) => q.id === id)
      // return { ...question, ...schema }
      return question
    }),
    indQues: category.indQues.map((id) => {
      const question = neededAssessmentMemQues.find((q) => q.id === id)
      // return { ...question, ...schema }
      return question
    }),
  }
})
// console.log(JSON.stringify(questions, null, 2))
